name: Test
on: [push]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - run: sed -i -E "s/([']docker:.+)/Dockerfile/" ./action.yml
      - run: echo -n '' > .dockerignore
      - uses: ./
